apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: replace-me
spec:
  ingressClassName: replace-me
  tls:
    - hosts:
        - sabnzbd.example.local
      secretName: sabnzbd-tls
  rules:
    - host: sabnzbd.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sabnzbd
                port:
                  number: 80
