apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: replace-me
spec:
  ingressClassName: replace-me
  tls:
    - hosts:
        - vaultwarden.example.local
      secretName: vaultwarden-tls
  rules:
    - host: vaultwarden.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80
