#cluster-issuer-cloudflare.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: shawnifoley@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cloudflare-private-key
    solvers:
      - dns01:
          cloudflare:
            email: shawnifoley@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret # Name of the Secret we created
              key: api-token # The key within the Secret
        selector:
          dnsZones:
            - "fol3y.us"
