apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn.yaml
  - nfs-storage.yaml
  - longhorn-backup-target.yaml
  - longhorn-recurring-jobs.yaml
  - cluster-issuer-cloudflare.yaml
