apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-sonarr-weekly
  namespace: longhorn-system
spec:
  cron: "50 2 * * 0"
  task: backup
  retain: 4
  concurrency: 1
  groups: []
  labels: {}
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-radarr-weekly
  namespace: longhorn-system
spec:
  cron: "52 2 * * 0"
  task: backup
  retain: 4
  concurrency: 1
  groups: []
  labels: {}
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-vaultwarden-daily
  namespace: longhorn-system
spec:
  cron: "51 2 * * *"
  task: backup
  retain: 14
  concurrency: 1
  groups: []
  labels: {}
