apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-export-root
spec:
  capacity:
    storage: 11Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=3
    - proto=tcp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.253
    path: /volume1/export
