---
- name: Copy master K3s service file
  ansible.builtin.template:
    src: "master-k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: "0644"

- name: Copy master K3s config.yaml file
  ansible.builtin.template:
    src: "master-config.yaml.j2"
    dest: "/etc/rancher/k3s/config.yaml"
    owner: root
    group: root
    mode: "0600"

- name: Enable and check K3s service on Master
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true

# primary master only
- name: Ensure k3s manifests directory exists
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0755"
  when:
    - is_primary_master | bool
    - k3s_api_vip is defined

- name: Install kube-vip manifest (auto-applied by k3s)
  ansible.builtin.template:
    src: "kube-vip.yaml.j2"
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
    owner: root
    group: root
    mode: "0644"
  when:
    - is_primary_master | bool
    - k3s_api_vip is defined

# kubeconfig handling
- name: Change k3s.yaml permissions to 0644 so it can be fetched
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: "0644"

- name: Fetch kubeconfig from first master only
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig_yaml }}"
    flat: true
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
