---
- name: Copy worker K3s service file
  ansible.builtin.template:
    src: "worker-k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Copy worker K3s config.yaml file
  ansible.builtin.template:
    src: "worker-config.yaml.j2"
    dest: "/etc/rancher/k3s/config.yaml"
    owner: root
    group: root
    mode: 0600

- name: Enable and check K3s service on Workers
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true
