---
- name: Install Longhorn
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_yaml }}"
    name: longhorn
    chart_ref: longhorn
    release_namespace: longhorn-system
    create_namespace: true
    chart_repo_url: https://charts.longhorn.io
    release_state: present
    chart_version: "{{ longhorn_chart_version }}"
