apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - extras/restart-sabnzbd-cronjob.yaml
  - extras/restart-sonarr-cronjob.yaml
  - extras/restart-radarr-cronjob.yaml
  - extras/restart-vaultwarden-cronjob.yaml

patches:
  - path: patches/sabnzbd-ingress.yaml
  - path: patches/sonarr-ingress.yaml
  - path: patches/radarr-ingress.yaml
  - path: patches/vaultwarden-ingress.yaml
  - path: patches/sonarr-config-pvc.yaml
  - path: patches/radarr-config-pvc.yaml
  - path: patches/vaultwarden-data-pvc.yaml
  - path: patches/image-pull-policy.yaml
