apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
  labels:
    recurring-job.longhorn.io/backup-sonarr-weekly: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replace-me
  resources:
    requests:
      storage: 2Gi
