apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: media
  labels:
    recurring-job.longhorn.io/backup-vaultwarden-daily: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replace-me
  resources:
    requests:
      storage: 2Gi
