apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media-namespace.yaml
  - storage/nfs-export-root-pvc.yaml
  - storage/sonarr-config-pvc.yaml
  - storage/radarr-config-pvc.yaml
  - storage/vaultwarden-data-pvc.yaml
  - apps/sabnzbd/deployment.yaml
  - apps/sabnzbd/service.yaml
  - apps/sabnzbd/ingress.yaml
  - apps/sonarr/deployment.yaml
  - apps/sonarr/service.yaml
  - apps/sonarr/ingress.yaml
  - apps/radarr/deployment.yaml
  - apps/radarr/service.yaml
  - apps/radarr/ingress.yaml
  - apps/vaultwarden/deployment.yaml
  - apps/vaultwarden/service.yaml
  - apps/vaultwarden/ingress.yaml
